# Exclude every file or folder starting with a dot.
exclude: ^\.
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        files: '(\.pyi?|wscript)$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch
        args:
          ["--branch", "main", "--pattern", "^releases*"]
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=100000"] # Set to max file size in GitHub
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys, --no-ensure-ascii]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        files: '(\.pyi?|wscript)$'
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
